DX-1071: Attempt to ignore Codecov upload issues

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -179,7 +179,7 @@ jobs:
       - name: Codecov Upload
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-        run: bundle exec rake codecov:upload
+        run: bundle exec rake codecov:upload || echo 'Codecov upload failed'
 
       - name: RuboCop
         run: bundle exec rubocop --fail-level warning --display-only-fail-level-offenses
